#! /bin/bash
:<<EOF
 *  $Id: dmpsw-config, 2014-08-16 21:47:33 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 30/07/2013
 *---------------------------------------------------
 *  Description:
 *      must in $DMPSWSYS/bin
 *---------------------------------------------------
EOF

#-----------------------------------------------------------------------
# function help
#          print help on available command line arguments and enabled

Help(){
cat<<EOF

Usage: dmpsw-config [OPTION...]

  --prefix                Print installation prefix of DAMPE Software
  --version               Print version for DAMPE Software
  --libs                  Print basic libraries
  --cflags                Print header path and compiler flags
  --include               Print header path
  --help                  Print help information

EOF
  exit 1
}

#-------------------------------------------------------------------

#   list all libraries of DMPSW
libs="-lDmpKernel -lDmpEvent -lDmpBase"
:<<EOF
for file in `ls ${DMPSWSYS}/lib`;do
  if [[ ${file} = *libDmp* && ${file} = *.so* ]];then
    file=${file/lib/-l}
    file=${file/\.so/}
    libs="$libs $file"
  fi
done
EOF

#-----------------------------------------------------------------------
# output
#       will be used while using DAMPE software.

out=""

while test $# -gt 0; do
  #case "$1" in
  #  -*=*)
  #    optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
  #    ;;
  #  *)
  #    optarg=
  #    ;;
  #esac

  case $1 in
    --prefix)
      out="$out $DMPSWSYS"
      ;;
   --libs)
      out="$out -L$DMPSWWORK/lib -L$DMPSWSYS/lib $libs"
      ;;
   --cflags)
      out="$out -I$DMPSWWORK/include -I$DMPSWSYS/include -fPIC -O3"   # add ?
      ;;
   --include)
      out="$out -I$DMPSWWORK/include -I$DMPSWSYS/include"
      ;;
   -?)
      Help
      ;;
   --help)
      Help
      ;;
   --version)
      out="DMPSW verison VERSION"  # How to set this automatically while installation ??
      ;;
  esac
  shift
done

### Output the stuff
echo $out


